apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: singleIngress1
  namespace: bigip-ingress
spec:
  backend:
    # The name of the Service you want to expose to external traffic
    serviceName: nginx-ingress/nginx-ingress
    servicePort: 80
