kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-seucirty-cm
  namespace: nginx-ingress
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.10.0",
            "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
            "label": "http",
            "remark": "WAF AS3 Example",
            "as3_tenant": {
                "class": "Tenant",
                "as3_basic_app": {
                    "class": "Application",
                    "template": "generic",
                    "basic_app": {
                        "class": "Service_HTTP",
                        "virtualAddresses": [
                            "10.10.2.70"
                        ],
                        "remark":"ingress: basic-demo",
                        "virtualPort": 80,
                        "pool": "as3_basic_pool"
                    },
                    "as3_basic_pool": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": []
                            }
                        ]
                    }
                },
                "as3_seucirty_app": {
                    "class": "Application",
                    "template": "generic",
                    "seucirty_app": {
                        "class": "Service_HTTP",
                        "virtualAddresses": [
                            "10.10.2.70"
                        ],
                        "remark":"ingress: waf-demo",
                        "virtualPort": 8080,
                        "pool": "as3_seucirty_pool",
                        "securityLogProfiles": [
                            {
                                "bigip": "/Common/Log all requests"
                            }
                        ],
                        "policyWAF": {
                            "use": "OWASPAutoTune"
                        }
                    },
                    "as3_seucirty_pool": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": []
                            }
                        ]
                    },
                    "OWASPAutoTune": {
                        "class": "WAF_Policy",
                        "url": "https://raw.githubusercontent.com/mdditt2000/f5-as3-declarations/master/Common_WAF_Policy.xml",
                        "ignoreChanges": true
                    }
                }
            }
        }
    }
