apiVersion: v1
kind: Service
metadata:
  name: f5-as3-basic-service
  namespace: nginx-ingress
  labels:
    app: f5-as3-basic-svc
    cis.f5.com/as3-tenant: as3_tenant
    cis.f5.com/as3-app: as3_basic_app
    cis.f5.com/as3-pool: as3_basic_pool
spec:
  ports:
  - name: as3-basic-svc
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
  selector:
    app: nginx-ingress-controller-b
---
apiVersion: v1
kind: Service
metadata:
  name: f5-as3-security-service
  namespace: nginx-ingress
  labels:
    app: f5-as3-security-svc
    cis.f5.com/as3-tenant: as3_tenant
    cis.f5.com/as3-app: as3_security_app
    cis.f5.com/as3-pool: as3_security_pool
spec:
  ports:
  - name: as3-security-svc
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
  selector:
    app: nginx-ingress-controller-b
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-basic-configmap
  namespace: nginx-ingress
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.10.0",
            "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
            "label": "http",
            "remark": "Basic AS3 Example",
            "as3_tenant": {
                "class": "Tenant",
                "as3_basic_app": {
                    "class": "Application",
                    "template": "generic",
                    "as3_basic_app": {
                        "class": "Service_HTTP",
                        "virtualAddresses": [
                            "10.192.75.101"
                        ],
                        "remark":"ingress: basic-demo",
                        "virtualPort": 80,
                        "pool": "as3_basic_pool"
                    },
                    "as3_basic_pool": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": []
                            }
                        ]
                    }
                }
            }
        }
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-security-configmap
  namespace: nginx-ingress
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.10.0",
            "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
            "label": "http",
            "remark": "security AS3 Example",
            "as3_tenant": {
                "class": "Tenant",
                "as3_security_app": {
                    "class": "Application",
                    "template": "generic",
                    "as3_security_app": {
                        "class": "Service_HTTP",
                        "virtualAddresses": [
                            "10.192.75.102"
                        ],
                        "remark":"ingress: security-demo",
                        "virtualPort": 80,
                        "pool": "as3_security_pool"
                    },
                    "as3_security_pool": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": []
                            }
                        ]
                    }
                }
            }
        }
    }
