apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: financial-reporting
spec:
  host: reporting.acmefinancial.net
  upstreams:
  - name: financial-reporting-v1
    service: financial-reporting-v1-svc
    port: 80
  routes:
  - path: /
    action:
      pass: financial-reporting-v1
