kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-configmap
  namespace: nginx-ingress
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
    	"class": "AS3",
    	"declaration": {
    		"class": "ADC",
    		"schemaVersion": "3.10.0",
    		"id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
    		"label": "http",
    		"remark": "WAF AS3 Example",
    		"as3_tenant": {
    			"class": "Tenant",
    			"as3_basic_app": {
    				"class": "Application",
    				"template": "generic",
    				"basic_app_https": {
    					"class": "Service_HTTPS",
    					"virtualAddresses": [
    						"10.10.2.70"
    					],
    					"remark": "ingress: basic-demo",
    					"virtualPort": 443,
    					"redirect80": true,
    					"serverTLS": "webtls",
    					"pool": "as3_basic_pool"
    				},
    				"as3_basic_pool": {
    					"class": "Pool",
    					"monitors": [
                            {"use": "http_nginxIngress_monitor"}
    					],
    					"members": [{
    						"servicePort": 8080,
    						"serverAddresses": []
    					}]
    				},
                    "http_nginxIngress_monitor": {
                        "class": "Monitor",
                        "monitorType": "http",
                        "interval": 5,
                        "protocol": "http",
                        "send": "GET /nginx-health\\r\\n\\r\\n",
                        "receive": "healthy",
                        "timeout": 16
                    },
    				"webtls": {
    					"class": "TLS_Server",
    					"certificates": [{
    						"certificate": "webcert"
    					}]
    				},
    				"webcert": {
    					"class": "Certificate",
    					"certificate": "-----BEGIN CERTIFICATE-----\nMIICnDCCAgWgAwIBAgIJAJ5n2b0OCEjwMA0GCSqGSIb3DQEBCwUAMGcxCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApXYXNoaW5ndG9uMRAwDgYDVQQHDAdTZWF0dGxlMRQwEgYDVQQKDAtmNV9OZXR3b3JrczEbMBkGA1UEAwwSc2FtcGxlLmV4YW1wbGUubmV0MB4XDTE3MTEyNjE5NTAyNFoXDTE4MDIyNTE5NTAyNFowZzELMAkGA1UEBhMCVVMxEzARBgNVBAgMCldhc2hpbmd0b24xEDAOBgNVBAcMB1NlYXR0bGUxFDASBgNVBAoMC2Y1X05ldHdvcmtzMRswGQYDVQQDDBJzYW1wbGUuZXhhbXBsZS5uZXQwgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBALEsuXmSXVQpYjrZPW+WiTBjn491mwZYT7Q92V1HlSBtM6WdWlK1aZN5sovfKtOX7Yrm8xa+e4o/zJ2QYLyyv5O+t2EGN/4qUEjEAPY9mwJdfzRQy6Hyzm84J0QkTuUJ/EjNuPji3D0QJRALUTzu1UqqDCEtiN9OGyXEkh7uvb7BAgMBAAGjUDBOMB0GA1UdDgQWBBSVHPNrGWrjWyZvckQxFYWO59FRFjAfBgNVHSMEGDAWgBSVHPNrGWrjWyZvckQxFYWO59FRFjAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4GBAJeJ9SEckEwPhkXOm+IuqfbUS/RcziifBCTmVyE+Fa/j9pKSYTgiEBNdbJeBEa+gPMlQtbV7Y2dy8TKx/8axVBHiXC5geDML7caxOrAyHYBpnx690xJTh5OIORBBM/a/NvaR+P3CoVebr/NPRh9oRNxnntnqvqD7SW0U3ZPe3tJc\n-----END CERTIFICATE-----",
    					"privateKey": "-----BEGIN RSA PRIVATE KEY-----\nProc-Type: 4,ENCRYPTED\nDEK-Info: AES-256-CBC,D8FFCE6B255601587CB54EC29B737D31\n\nkv4Fc3Jn0Ujkj0yRjt+gQQfBLSNF2aRLUENXnlr7Xpzqu0Ahr3jS1bAAnd8IWnsR\nyILqVmKsYF2DoHh0tWiEAQ7/y/fe5DTFhK7N4Wml6kp2yVMkP6KC4ssyYPw27kjK\nDBwBZ5O8Ioej08A5sgsLCmglbmtSPHJUn14pQnMTmLOpEtOsu6S+2ibPgSNpdg0b\nCAJNG/KHe+Vkx59qNDyDeKb7FZOlsX30+y67zUq9GQqJEDuysPJ2BUNP0IJXAjst\nFIt1qNoZew+5KDYs7u/lPxcMGTirUhgI84Jy4WcDvSOsP/tKlxj04TbIE3epmSKy\n+TihHkwY7ngIGtcm3Sfqk5jz2RXoj1/Ac3SW8kVTYaOUogBhn7zAq4Wju6Et4hQG\nRGapsJp1aCeZ/a4RCDTxspcKoMaRa97/URQb0hBRGx3DGUhzpmX9zl7JI2Xa5D3R\nmdBXtjLKYJTdIMdd27prBEKhMUpae2rz5Mw4J907wZeBq/wu+zp8LAnecfTe2nGY\nE32x1U7gSEdYOGqnwxsOexb1jKgCa67Nw9TmcMPV8zmH7R9qdvgxAbAtwBl1F9OS\nfcGaC7epf1AjJLtaX7krWmzgASHl28Ynh9lmGMdv+5QYMZvKG0LOg/n3m8uJ6sKy\nIzzvaJswwn0j5P5+czyoV5CvvdCfKnNb+3jUEN8I0PPwjBGKr4B1ojwhogTM248V\nHR69D6TxFVMfGpyJhCPkbGEGbpEpcffpgKuC/mEtMqyDQXJNaV5HO6HgAJ9F1P6v\n5ehHHTMRvzCCFiwndHdlMXUjqSNjww6me6dr6LiAPbejdzhL2vWx1YqebOcwQx3G\n-----END RSA PRIVATE KEY-----",
    					"passphrase": {
    						"ciphertext": "ZjVmNQ==",
    						"protected": "eyJhbGciOiJkaXIiLCJlbmMiOiJub25lIn0"
    					}
    				}
    			},
    			"as3_security_app": {
    				"class": "Application",
    				"template": "generic",
    				"basic_app_https-Redirect": {
    					"class": "Service_HTTP",
    					"virtualAddresses": [
    						"10.10.2.70"
    					],
    					"iRules": [
    						{"use": "Redirect_iRule_8443"}
    					],
    					"remark": "ingress: waf-demo-redirect",
    					"virtualPort": 8080
    				},
    				"seucirty_app_https": {
    					"class": "Service_HTTPS",
    					"virtualAddresses": [
    						"10.10.2.70"
    					],
    					"remark": "ingress: waf-demo",
    					"virtualPort": 8443,
    					"pool": "as3_security_pool",
    					"redirect80": false,
    					"serverTLS": "webtls",
    					"securityLogProfiles": [{
    						"bigip": "/Common/Log all requests"
    					}],
    					"policyWAF": {
    						"use": "OWASPAutoTune"
    					}
    				},
    				"webtls": {
    					"class": "TLS_Server",
    					"certificates": [{
    						"certificate": "webcert"
    					}]
    				},
    				"webcert": {
    					"class": "Certificate",
    					"certificate": "-----BEGIN CERTIFICATE-----\nMIICnDCCAgWgAwIBAgIJAJ5n2b0OCEjwMA0GCSqGSIb3DQEBCwUAMGcxCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApXYXNoaW5ndG9uMRAwDgYDVQQHDAdTZWF0dGxlMRQwEgYDVQQKDAtmNV9OZXR3b3JrczEbMBkGA1UEAwwSc2FtcGxlLmV4YW1wbGUubmV0MB4XDTE3MTEyNjE5NTAyNFoXDTE4MDIyNTE5NTAyNFowZzELMAkGA1UEBhMCVVMxEzARBgNVBAgMCldhc2hpbmd0b24xEDAOBgNVBAcMB1NlYXR0bGUxFDASBgNVBAoMC2Y1X05ldHdvcmtzMRswGQYDVQQDDBJzYW1wbGUuZXhhbXBsZS5uZXQwgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBALEsuXmSXVQpYjrZPW+WiTBjn491mwZYT7Q92V1HlSBtM6WdWlK1aZN5sovfKtOX7Yrm8xa+e4o/zJ2QYLyyv5O+t2EGN/4qUEjEAPY9mwJdfzRQy6Hyzm84J0QkTuUJ/EjNuPji3D0QJRALUTzu1UqqDCEtiN9OGyXEkh7uvb7BAgMBAAGjUDBOMB0GA1UdDgQWBBSVHPNrGWrjWyZvckQxFYWO59FRFjAfBgNVHSMEGDAWgBSVHPNrGWrjWyZvckQxFYWO59FRFjAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4GBAJeJ9SEckEwPhkXOm+IuqfbUS/RcziifBCTmVyE+Fa/j9pKSYTgiEBNdbJeBEa+gPMlQtbV7Y2dy8TKx/8axVBHiXC5geDML7caxOrAyHYBpnx690xJTh5OIORBBM/a/NvaR+P3CoVebr/NPRh9oRNxnntnqvqD7SW0U3ZPe3tJc\n-----END CERTIFICATE-----",
    					"privateKey": "-----BEGIN RSA PRIVATE KEY-----\nProc-Type: 4,ENCRYPTED\nDEK-Info: AES-256-CBC,D8FFCE6B255601587CB54EC29B737D31\n\nkv4Fc3Jn0Ujkj0yRjt+gQQfBLSNF2aRLUENXnlr7Xpzqu0Ahr3jS1bAAnd8IWnsR\nyILqVmKsYF2DoHh0tWiEAQ7/y/fe5DTFhK7N4Wml6kp2yVMkP6KC4ssyYPw27kjK\nDBwBZ5O8Ioej08A5sgsLCmglbmtSPHJUn14pQnMTmLOpEtOsu6S+2ibPgSNpdg0b\nCAJNG/KHe+Vkx59qNDyDeKb7FZOlsX30+y67zUq9GQqJEDuysPJ2BUNP0IJXAjst\nFIt1qNoZew+5KDYs7u/lPxcMGTirUhgI84Jy4WcDvSOsP/tKlxj04TbIE3epmSKy\n+TihHkwY7ngIGtcm3Sfqk5jz2RXoj1/Ac3SW8kVTYaOUogBhn7zAq4Wju6Et4hQG\nRGapsJp1aCeZ/a4RCDTxspcKoMaRa97/URQb0hBRGx3DGUhzpmX9zl7JI2Xa5D3R\nmdBXtjLKYJTdIMdd27prBEKhMUpae2rz5Mw4J907wZeBq/wu+zp8LAnecfTe2nGY\nE32x1U7gSEdYOGqnwxsOexb1jKgCa67Nw9TmcMPV8zmH7R9qdvgxAbAtwBl1F9OS\nfcGaC7epf1AjJLtaX7krWmzgASHl28Ynh9lmGMdv+5QYMZvKG0LOg/n3m8uJ6sKy\nIzzvaJswwn0j5P5+czyoV5CvvdCfKnNb+3jUEN8I0PPwjBGKr4B1ojwhogTM248V\nHR69D6TxFVMfGpyJhCPkbGEGbpEpcffpgKuC/mEtMqyDQXJNaV5HO6HgAJ9F1P6v\n5ehHHTMRvzCCFiwndHdlMXUjqSNjww6me6dr6LiAPbejdzhL2vWx1YqebOcwQx3G\n-----END RSA PRIVATE KEY-----",
    					"passphrase": {
    						"ciphertext": "ZjVmNQ==",
    						"protected": "eyJhbGciOiJkaXIiLCJlbmMiOiJub25lIn0"
    					}
    				},
    				"Redirect_iRule_8443": {
    					"class": "iRule",
    					"iRule": "when HTTP_REQUEST {\n   HTTP::respond 307 location https://[HTTP::host]:8443/[HTTP::uri]\n}\n",
    					"expand": true
    				},
    				"as3_security_pool": {
    					"class": "Pool",
    					"monitors": [
                            {"use": "http_nginxIngress_monitor"}
    					],
    					"members": [{
    						"servicePort": 8080,
    						"serverAddresses": []
    					}]
    				},
                    "http_nginxIngress_monitor": {
                        "class": "Monitor",
                        "monitorType": "http",
                        "interval": 5,
                        "protocol": "http",
                        "send": "GET /nginx-health\\r\\n\\r\\n",
                        "receive": "healthy",
                        "timeout": 16
                    },
    				"OWASPAutoTune": {
    					"class": "WAF_Policy",
    					"url": "https://raw.githubusercontent.com/mdditt2000/f5-as3-declarations/master/Common_WAF_Policy.xml",
    					"ignoreChanges": true
    				}
    			}
    		}
    	}
    }
